### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by random-robbie** [agrawalsmart7/autocon#1]
```
root@ubuntu-s-1vcpu-1gb-lon1-01:~/subs/autocon# python autocon.py -t google.com -f anyfilename.txt -o anyfilename.html
Traceback (most recent call last):
  File "autocon.py", line 8, in <module>
    import runner
  File "/root/subs/autocon/runner.py", line 2, in <module>
    import subdomainenum
  File "/root/subs/autocon/Phase-list/subdomainenum.py", line 5, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

Python 2.7.12

**Comment by agrawalsmart7** [comment]
Hi Random Robbie, 

I have run this tool in Kali Linux environment and that works well. I am not sure why you are facing this. Hope that you have installed all the dependencies which are mentioned in requirements.txt. 

If you are done so, then you might need to update bs4 and html5lib. 

Thanks, looking for your reply.
